### ISSUE TITLE
Fatal error: Call to a member function find() on a non-object in /app/code/community/Zendesk/Zendesk/Model/Observer.php on line 75 

### ISSUE THREAD

**Issue by maxcamo** [agnostack/magento_extension#145]

**Comment by maxcamo** [comment]
Hello, i have this error
Fatal error: Call to a member function find() on a non-object in /app/code/community/Zendesk/Zendesk/Model/Observer.php on line 75 

on this line

if (! empty($zDomain)) {
            if ((bool) Mage::getStoreConfig('zendesk/frontend_features/web_widget_code_active')) {
                **$embeds = Mage::getModel('zendesk/api_configsets')->find();**
                if (! isset($embeds['launcher'])) {
                    Mage::getModel('zendesk/api_configsets')->initialize();
                }
            }

**Comment by centexdabull** [comment]
Any info on this issue?

**Comment by nacho2706** [comment]
There's an error into the getModel function initialization. The proper way to call to that find() function is:
$embeds = Mage::getModel('zendesk/api_config**S**ets')->find();

also it's necessary to update the line:
Mage::getModel('zendesk/api_configsets')->initialize();
for
Mage::getModel('zendesk/api_config**S**ets')->initialize();

Let me know if you have any questions.

Best,
