### ISSUE TITLE
Re-architect models

### ISSUE THREAD

**Issue by vbuck** [agnostack/magento_extension#37]
First, thanks for everyone's work on this. This module is very useful. However, I personally feel that the architecture of models is too much astray from core Magento modeling conventions.

For example, `Mage::getModel('zendesk/api_tickets')->get(1)` loader ought to instead have its method named `load` as in `Mage_Core_Model_Abstract`.

Also, `Zendesk_Zendesk_Model_Api_Abstract::_call` should really be part of a resource model, as to emulate the data mapper design patterns of Magento.

In following these kinds of patterns, this module will be much easier to extend and develop with, as developers will have a natural syntax to follow.

**Comment by jwswj** [comment]
Great feedback @vbuck. We're not planning a re-architecture of the project at the moment, but I'm sure it will come up soon. Closing this for now, but will keep it in mind.
