### ISSUE TITLE
Strict notices when visiting admin grid page

### ISSUE THREAD

**Issue by rutgerrademaker** [agnostack/magento_extension#50]
When visiting the Zendesk > Dashboard page in the admin 2 Strict notices appear in system.log

Strict Notice: Only variables should be passed by reference  in /app/code/community/Zendesk/Zendesk/Block/Adminhtml/Dashboard/Grids.php on line 72
Strict Notice: Only variables should be passed by reference  in /app/code/community/Zendesk/Zendesk/Block/Adminhtml/Dashboard/Grids.php on line 76

using version 1.4.0 of the extension in magento EE 1.12.0.2

PHP 5.4.4-14+deb7u5 (cli) (built: Oct  3 2013 09:24:58) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2012 Zend Technologies

**Notes** 
To be able to reproduce this, at least 1 view must be chosen under Zendesk > Configuration ("Views to show on dashboards")

**Comment by joseconsador** [comment]
fixed
