### ISSUE TITLE
Zendesk Host Mapping - Email Misconfiguration

### ISSUE THREAD

**Issue by dfrankland** [agnostack/magento_extension#63]
When one changes Zendesk's host mapping from "yourdomain.zendesk.com" to "yoursubdomain.yourdomain.com" or any other "yourdomain.com" through Zendesk's settings, under "Account" > "Branding" > "Host Mapping", the Zendesk Magento extension can use the new host mapping as the "Zendesk Domain" under the "General" configuration of the extension. The API and mostly everything works except one thing...

If one also selects "Yes" for "Create tickets from Contact Us form" in the Zendesk Magento extension, under the "Customer Frontend" configuration, this silently changes the Contact Us form's email to "support@youdsubdomain.yourdomain.com" or "support@youdomain.com". This email might not exist which leads to lots of missing Contact Us form submissions. The "Zendesk Domain" should enforce only "yourdomain.zendesk.com" URLs or check for the "yourdomain.zendesk.com" using the API and set the Contact Us form email as such.

**Comment by joseconsador** [comment]
PR merged

**Comment by jwswj** [comment]
Fix will be included in the next release.
