### ISSUE TITLE
Memory leak on admin order creation

### ISSUE THREAD

**Issue by ShopJimmy** [agnostack/magento_extension#70]
I haven't looked into what is causing it, but while this module is enabled we are unable to place orders under customer accounts who have thousands of orders because it exceeds the PHP memory limit.

If i find anything i will update.

**Comment by jwswj** [comment]
Weird one @ShopJimmy - we haven't had that reported before. Did you dig into it further at all? Would be great to get to the bottom of it.

**Comment by joseconsador** [comment]
@ShopJimmy what is PHP's `memory_limit` set to on your servers? I was able to replicate this with 10,000 orders on a customer but I had to set my `memory_limit` to **32M**. Magento recommends at least **256M** . 

I have confirmed that pull request #88 addresses this issue but I'd still suggest to increase the memory_limit on your end.

**Comment by EmeryEx** [comment]
We're at 512M and customers with up to 40k orders (mostly API driven) but there are other modules using memory on order placement and also when that order collection is loaded. In any case, raising memory allowance is only a temporary fix.
