### ISSUE TITLE
SSO not working after SUPEE-6285 patch

### ISSUE THREAD

**Issue by leeuwd** [agnostack/magento_extension#80]
Because of patch, `Mage_Adminhtml_Controller_Action::_isAllowed()` changed from a default `true` to `Mage::getSingleton('admin/session')->isAllowed('admin')`. Extensions should now override this method in order to work for custom ACL users.

Quick fix is adding the following to `ZendeskController.php`:

```
protected function _isAllowed() {
     return true;
}
```

The Zendesk plugin should use proper ACL for this, like: `return Mage::getSingleton('admin/session')->isAllowed('ENTER RESOURCE IDENTIFIER HERE');`

**Comment by jwswj** [comment]
Thanks @leeuwd https://github.com/zendesk/magento_extension/pull/82 resolves this issue and is now available on master and Magneto Connect
