### ISSUE TITLE
Magento app unable to connect (i.e., authorise)

### ISSUE THREAD

**Issue by leeuwd** [agnostack/magento_extension#83]
On our specific environment, the Magento app inside Zendesk was not able to connect. I fixed it by adding the following lines to `Zendesk_Zendesk_ApiController`:

```
if (!$tokenString && isset($_SERVER['REDIRECT_REMOTE_USER'])) {
     $tokenString = $_SERVER['REDIRECT_REMOTE_USER'];
}
```

**Comment by jwswj** [comment]
Thanks @leeuwd
