### ISSUE TITLE
Duplicate User field creation when initial customer sync failed

### ISSUE THREAD

**Issue by hannesbe** [agnostack/magento_extension#91]
We had some customer e-mail addresses with invalid chars in it that somehow ended up in Magento. I don't know how they got there, because Magento wouldn't normally accept those. Anyway, it caused the initial sync to fail at those customers, because Zendesk didn't accept the invalid address. 

The actual problem is that when you run the sync again (after I fixed those invalid addresses), it tries to create the Zendesk user fields again, while they already exist from the initial (failed) sync and exits with an error ('Key: has already been taken'). 

I worked around it by deleting the user fields in Zendesk, but maybe the sync should store that those fields have been created earlier in the sync to prevent this.

**Comment by joseconsador** [comment]
A fix for this has been release with v2.1.1 . Thanks for the feedback.
